# Generated by Django 4.1.7 on 2023-04-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField()),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField()),
                ('desc', models.CharField(max_length=100)),
                ('dest', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pellet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inbound', models.BooleanField(default=True)),
                ('column', models.CharField(max_length=8)),
                ('row', models.CharField(max_length=8)),
                ('pellet_name', models.CharField(max_length=32)),
                ('pellet_desc', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('destination', models.CharField(max_length=50, null=True)),
                ('inbound_shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AssetMgr.inbound')),
                ('outbound_shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AssetMgr.outbound')),
            ],
            options={
                'unique_together': {('column', 'row')},
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('barcode', models.CharField(max_length=100)),
                ('on_pellet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetMgr.pellet')),
            ],
        ),
    ]
