# Generated by Django 4.1.7 on 2023-04-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pellet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inbound', models.BooleanField(default=True)),
                ('column', models.CharField(max_length=8)),
                ('row', models.CharField(max_length=8)),
                ('pellet_name', models.CharField(max_length=32)),
                ('pellet_desc', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('destination', models.CharField(max_length=50, null=True)),
            ],
            options={
                'unique_together': {('column', 'row')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('destination', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('order_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetMgr.products')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50, null=True)),
                ('arrival_date', models.DateField()),
                ('origin', models.CharField(max_length=50, null=True)),
                ('due_outbound_date', models.DateField(null=True)),
                ('name', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetMgr.products')),
                ('on_pellet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetMgr.pellet')),
            ],
        ),
    ]
