# Generated by Django 4.2 on 2023-04-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssetMgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='cargo',
            name='on_pellet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetMgr.pellet'),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pellet',
            name='inbound_shipment',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='AssetMgr.inbound'),
        ),
        migrations.AlterField(
            model_name='pellet',
            name='outbound_shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetMgr.outbound'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('quantity', models.IntegerField(max_length=8)),
                ('destination', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('order_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetMgr.products')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AssetMgr.products'),
        ),
    ]
