# Generated by Django 4.2 on 2023-04-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetMgr', '0002_products_alter_cargo_on_pellet_alter_outbound_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
