# Generated by Django 4.1.7 on 2023-04-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetMgr', '0003_alter_cargo_is_in_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pellet',
            name='pellet_desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
