# Generated by Django 4.1.7 on 2023-04-26 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AssetMgr', '0004_alter_cargo_desc_alter_pellet_pellet_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pellet',
            name='inbound_shipment',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pellet',
            name='outbound_shipment',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
