# Generated by Django 4.1.7 on 2023-04-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetMgr', '0005_pellet_inbound_shipment_pellet_outbound_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pellet',
            name='outbound_shipment',
            field=models.DateField(null=True),
        ),
    ]
