# Generated by Django 4.1.7 on 2023-04-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetMgr', '0006_alter_pellet_outbound_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
