# Generated by Django 4.1.7 on 2023-05-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetMgr', '0007_alter_products_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pellet',
            name='inbound_shipment',
        ),
        migrations.RemoveField(
            model_name='pellet',
            name='outbound_shipment',
        ),
    ]
